#include <string>

enum TokenType {
	// Separator/punctuator
	// LEFT_PAREN, RIGHT_PAREN,
	LEFT_BRACE, RIGHT_BRACE,
	COLON,
	SEMICOLON,

	// Operators
	PLUS, MINUS, STAR, SLASH,
	AND, OR,

	BANG, BANG_EQUAL,
	EQUAL,
	GREATER, GREATER_EQUAL,
	LESS, LESS_EQUAL,

	// literals
	NUMBER, STRING,

	IDENTIFIER,

	// keywords
	IF, ELSE,
	DEF,
	PRINT, CHAR_PRINT, PEEK, CHAR_PEEK,
	DUP,
	SWAP, N_SWAP,
	INPUT, CHAR_INPUT,

	// comments
	// HASHTAG,

	// for parser
	END
};

// a data class for tokens generated by the scanner.
struct Token {
	TokenType type;
	std::string lexeme;
	int literal;
	int line;
};
